version: '3.1'

services:

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
     -  target: 3306
        published: 5000
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LausaMart
      MYSQL_DATABASE: Lausa